[versions]
version_accompanist_pager = "0.36.0"
version_accompanist_permissions = "0.37.3"
version_android_gradle = "9.2.1"
version_annotations = "26.1.0"
version_core = "1.54.0"
version_core_ktx = "1.18.0"
version_kotlin = "2.3.21"
version_ksp = "2.3.8"
version_junit = "4.13.2"
version_junitTest_Ext = "1.3.0"
espressoCore = "3.7.0"
version_lifecycle_viewmodel_ktx = "2.10.0"
version_lottie = "6.7.1"
version_lottie_compose = "6.7.1"

version_moshi = "1.15.2"
version_retrofit = "3.0.0"
version_okhttp = "5.3.2"
version_gson = "2.14.0"

version_androidx_browser = "1.10.0"
version_kotlinx_immutable_collections = "0.4.0"
version_kotlinx_coroutines_test = "1.11.0"
version_coil = "2.7.0"
version_coil3= "3.4.0"
version_compose_navigation = "2.9.8"
version_turbine = "1.2.1"
version_appcompat = "1.7.1"
version_material = "1.14.0"

version_androidx_preference = "1.2.1"
version_security_crypto = "1.1.0"
version_desugar = "2.1.5"
version_android_sqlight = "2.2.0"
version_sqlight_framework = "2.4.0"
version_sql_cipher = "4.16.0"
version_sqlite = "2.6.2"
#version_sql_cipher = "4.11.0"

version_chucker = "4.3.1"

version_firebase_bom = "34.13.0"
version_amplitude_analytics = "1.+"
version_room = "2.8.4"
version_hilt = "2.59.2"
version_android_hilt_compiler = "1.3.0"
version_hilt_navigation_compose = "1.3.0"

version_work_runtime_ktx = "2.11.2"
version_androidx_compose_bom = "2026.05.01"

version_timber = "5.0.1"
version_constraintlayout = "2.2.1"
version_constraintlayout_compose = "1.1.1"
version_activity = "1.12.2"
version_activity_ktx = "1.13.0"
version_fragment_ktx = "2.9.8"
version_navigation_ui_ktx = "2.9.8"

version_google_play_services = "4.4.4"
version_secrets_gradle_plugin = "2.0.1"
version_crashlytics = "3.0.7"
version_location_services = "21.3.0"
version_maps_services = "20.0.0"
version-app-update = "2.1.0"
version-app-review = "2.0.2"

version_camerax= "1.6.1"
version_compression_zelory = "3.0.1"

version_play_services_maps = "19.2.0"
version_maps_compose = "8.3.0"
version_app_maven_publish = "maven-publish"
version_paging_compose = "3.5.0"
version_lifecycle_process = "2.10.0"
version_lifecycle_runtime_ktx = "2.10.0"

#  ndk versions/ used in app host gradles
ndkVersion = "29.0.14206865"
cMakeVersion = "3.22.1"
appcompatVersion = "1.7.1"
firebaseConfigKtxVersion = "23.1.0"
foundationLayoutVersion = "1.11.2"


[libraries]
#core-module-dev-gms = { group = "com.alimapps.android.core.dev.gms", name = "ANCoreModule", version.ref = "coreVersion" }
#core-module-dev-hms = { group = "com.alimapps.android.core.dev.hms", name = "ANCoreModule", version.ref = "coreVersion" }
#core-module-qa-gms = { group = "com.alimapps.android.core.qa.gms", name = "ANCoreModule", version.ref = "coreVersion" }
#core-module-qa-hms = { group = "com.alimapps.android.core.qa.hms", name = "ANCoreModule", version.ref = "coreVersion" }
#core-module-stg-gms = { group = "com.alimapps.android.core.stg.gms", name = "ANCoreModule", version.ref = "coreVersion" }
#core-module-stg-hms = { group = "com.alimapps.android.core.stg.hms", name = "ANCoreModule", version.ref = "coreVersion" }
#core-module-gms = { group = "com.alimapps.android.core", name = "ANCoreModuleGMS", version.ref = "coreVersion" }
#core-module-hms = { group = "com.alimapps.android.core", name = "ANCoreModuleHMS", version.ref = "coreVersion" }

accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "version_accompanist_pager" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "version_accompanist_pager" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "version_activity_ktx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "version_activity_ktx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "version_lifecycle_process" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "version_lifecycle_viewmodel_ktx" }
annotations = { module = "org.jetbrains:annotations", version.ref = "version_annotations" }
google-ar-core = { module = "com.google.ar:core", version.ref = "version_core" }


ksp-lib = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "version_ksp" }
kotlin-std = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "version_kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "version_kotlin" }
android-hilt = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "version_hilt" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "version_accompanist_permissions" }
android-tools-build-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "version_android_gradle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "version_core_ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "version_lifecycle_runtime_ktx" }

androidx-browser = { module = "androidx.browser:browser", version.ref = "version_androidx_browser" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "version_kotlin" }
kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "version_kotlinx_immutable_collections" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "version_kotlinx_coroutines_test" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "version_ksp" }


androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "version_androidx_compose_bom" }
androidx-compose-activity = { module = "androidx.activity:activity-compose"}
androidx-compose-animation-android = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation-android = { module = "androidx.compose.foundation:foundation-android" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "version_constraintlayout_compose" }
androidx-compose-graphics = { module = "androidx.compose.ui:ui-graphics"}
androidx-compose-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime"}
androidx-compose-runtime-android = { module = "androidx.compose.runtime:runtime-android" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling"}
androidx-compose-ui-text-android = { module = "androidx.compose.ui:ui-text-android" }
androidx-compose-ui-graphics-android = { module = "androidx.compose.ui:ui-graphics-android"}
androidx-compose-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose"}

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "version_hilt_navigation_compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref ="version_compose_navigation" }

androidx-compose-ui-testing-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-testing-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }


#for hilt ksp compile
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "version_hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "version_hilt" }
# for old version/ kapt
#hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "version_hilt" }//
# Optional: Only for WorkManager support
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "version_android_hilt_compiler" }



androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "version_appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "version_material" }

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "version_constraintlayout" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "version_fragment_ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "version_navigation_ui_ktx" }

androidx-camera = { module = "androidx.camera:camera-camera2", version.ref = "version_camerax" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "version_camerax" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "version_camerax" }
androidx-camera-compose = { module = "androidx.camera:camera-compose", version.ref = "version_camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "version_camerax" }

androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "version_work_runtime_ktx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "version_paging_compose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "version_paging_compose" }
androidx-paging-common-android = { module = "androidx.paging:paging-common-android", version.ref = "version_paging_compose" }

androidx-preference = { module = "androidx.preference:preference", version.ref = "version_androidx_preference" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "version_room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "version_room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "version_room" }
#sql-cipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "version_sql_cipher" }
sql-cipher = { module = "net.zetetic:sqlcipher-android", version.ref = "version_sql_cipher" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "version_security_crypto" }
android-sqlite = { module = "com.android.tools:sqlite", version.ref = "version_android_sqlight" }
androidx-sqlite = { group = "androidx.sqlite", name = "sqlite", version.ref = "version_sqlite" }
androidx-sqlite-framwork = { module = "androidx.sqlite:sqlite-framework", version.ref = "version_sqlight_framework" }

gms-location = { module = "com.google.android.gms:play-services-location", version.ref = "version_location_services" }
gms-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "version_maps_services" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "version_maps_compose" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "version_firebase_bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-pref = { group = "com.google.firebase", name = "firebase-perf" }
firebase-remote-config = { group = "com.google.firebase", name = "firebase-config" }

amplitude-analytics = { module = "com.amplitude:analytics-android", version.ref = "version_amplitude_analytics" }

#ksp-lib = { group = "com.google.devtools.ksp:symbol-processing-api", version.ref = "version_ksp" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "version_lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "version_lottie_compose" }


google-play-update = { group = "com.google.android.play", name = "app-update", version.ref = "version-app-update" }
google-play-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "version-app-update" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref = "version-app-review" }
google-play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "version-app-review" }


google-gson = { module = "com.google.code.gson:gson", version.ref = "version_gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "version_retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "version_retrofit" }
retrofit-convertor-scalor = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "version_retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "version_okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "version_okhttp"}
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "version_moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "version_moshi" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "version_kotlin" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "version_coil" }
coil-compose3 = { module = "io.coil-kt.coil3:coil-compose", version.ref = "version_coil3" }

compressor = { module = "id.zelory:compressor", version.ref = "version_compression_zelory" }

chucker-debug = { group = "com.github.ChuckerTeam.Chucker", name = "library", version.ref = "version_chucker" }
chucker-release = { group = "com.github.ChuckerTeam.Chucker", name = "library-no-op", version.ref = "version_chucker" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "version_junitTest_Ext" }
junit = { module = "junit:junit", version.ref = "version_junit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "version_turbine" }
timber-lib = { module = "com.jakewharton.timber:timber", version.ref = "version_timber" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayoutVersion" }

[plugins]
android-lint = { id = "com.android.lint", version.ref = "version_android_gradle" }
android-application = { id = "com.android.application", version.ref = "version_android_gradle" }
android-library = { id = "com.android.library", version.ref = "version_android_gradle" }
ksp = { id = "com.google.devtools.ksp", version.ref = "version_ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "version_hilt" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "version_kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "version_kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "version_kotlin" }

firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "version_crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "version_google_play_services" }
google-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "version_secrets_gradle_plugin" }

## centralize build config Plugins defined by this project
letsConnect-maven-publish = { id = "maven-publish", version = "unspecified" }
letsConnect-appHost = { id = "convention.appplicationModule", version = "unspecified" }
letsConnect-appDataModule = { id = "convention.dataModule", version = "unspecified" }
letsConnect-appUiModule = { id = "convention.uiModule", version = "unspecified" }
letsConnect-appFeaturesModule = { id = "convention.featureModule", version = "unspecified" }
letsConnect-appFlavors = { id = "convention.appFlavors", version = "unspecified" }
letsConnect-appFlavorsEndPoint = { id = "convention.appFlavorsEndPoint", version = "unspecified" }
letsConnect-appRefreshDependencies = { id = "convention.appRefreshDependencies", version = "unspecified" }

[bundles]
group-android-ui = [
    "androidx-browser",
    "androidx-activity",
    "material",
    "annotations",
    "androidx-activity-ktx",
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-appcompat",
    "androidx-constraintlayout",
    "androidx-lifecycle-process",
    "kotlinx-immutable-collections"
]

group-compose-ui = [
    "coil-compose",
    "androidx-compose-ui",
    "androidx-compose-icons",
    "androidx-compose-preview",
    "androidx-compose-material3",
    "androidx-compose-activity",
    "androidx-compose-graphics",
    "androidx-compose-ui-text-android",
    "androidx-compose-runtime",
    "androidx-compose-runtime-android",
#    "androidx-compose-constraintlayout",
    "androidx-compose-animation-android",
    "androidx-compose-foundation-android",
    "androidx-compose-ui-graphics-android",
    "androidx-compose-ui-tooling-preview-android"
]

group-compose-navigation = [
    "androidx-hilt-navigation-compose",
    "androidx-compose-navigation",

]
group-navigation = [
    "androidx-navigation-fragment-ktx",
    "androidx-navigation-ui-ktx"
]
group_network = [
    "retrofit",
    "retrofit-converter-gson",
    "retrofit-convertor-scalor",
    "okhttp",
    "okhttp-logging-interceptor",
    "google-gson",
]

group-test-unit = [
    "junit",
    "kotlinx-coroutines-test",
    "turbine"
]
group-compose-test = [
    "androidx-compose-ui-testing-junit4",
    "androidx-compose-ui-testing-manifest",
]
group-android-test = [
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-compose-ui-testing-manifest",
]

group-room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]
group-security = [
    "sql-cipher",
#    "androidx-sqlite",
    "androidx-security-crypto",
]

work-manager = [
    "androidx-work-runtime-ktx",
]

group-accompanist-pager = [
    "accompanist-pager",
    "accompanist-pager-indicators",
]

group-paging = [
    "androidx-paging-runtime",
    "androidx-paging-compose",
    "androidx-paging-common-android",
]

group-firebase = [
    "firebase-pref",
    "firebase-messaging",
    "firebase-analytics",
    "firebase-crashlytics",
    "firebase-remote-config"
]

group-gms-map-location = [
    "gms-location",
    "gms-maps"
]

group-google-play-update = [
    "google-play-update",
    "google-play-review",
    "google-play-update-ktx",
    "google-play-review-ktx"
]

group-camera = [
    "androidx-camera",
    "androidx-camera-lifecycle",
    "androidx-camera-view",
    "compressor",
    "androidx-camera-core",
    "androidx-camera-compose"
]

