package com.alim.letsconnect.core.remoteconfig

object RemoteConfigFeaturesConstants {
    const val FEATURE_DEFAULTS_LIST = "features_defaults"
    
    object Dashboard {
        const val DASHBOARD_SEARCH = "UC-SHE-SEARCH"
        const val DASHBOARD_WEATHER_BANNER = "UC-SHE-WEATHER-BANNER"
        const val DASHBOARD_APPOINTMENT = "UC-SHE-DASHBOARD-APPOINTMENT"
        const val DASHBOARD_MY_DOCTORS = "UC-SHE-MY-DOCTORS"
        const val DASHBOARD_DAILY_ACTIVITY = "UC-SHE-DAILY-ACTIVITY"
        const val DASHBOARD_AS3AFNY = "UC-SHE-AS3AFNY"
        const val DASHBOARD_DYNAMIC_BANNER = "UC-SHE-DYNAMIC-BANNER"
        const val DASHBOARD_COMPLAIN= "url_for_937"
    }
    
    object Notification {
        const val NOTIFICATION = "UC-SHE-NOTIFICATION"
        const val NOTIFICATION_DELETE = "UC-SHE-NOTIFICATION-FL01-DELETE"
        const val NOTIFICATION_PRIVATE = "UC-SHE-NOTIFICATION-FL02-PRIVATE"
        const val NOTIFICATION_GENERAL = "UC-SHE-NOTIFICATION-FL03-GENERAL"
    }
    
    object SideMenu {
        const val SIDE_MENU = "UC-SHE-SIDE-MENU"
        const val SIDE_MENU_SETTINGS = "UC-SHE-SIDE-MENU-FL01-SETTINGS"
        const val SIDE_MENU_SETTINGS_DELETE_ACCOUNT =
            "UC-SHE-SIDE-MENU-FL01-SETTINGS-FL01-DELETE-ACCOUNT"
        const val SIDE_MENU_SETTINGS_CHANGE_PASSWORD =
            "UC-SHE-SIDE-MENU-FL01-SETTINGS-FL02-CHANGE-PASSWORD"
        const val SIDE_MENU_SETTINGS_ENABLE_BIO_METRICS =
            "UC-SHE-SIDE-MENU-FL01-SETTINGS-FL03-ENABLE-BIO-METRICS"
        const val SIDE_MENU_ABOUT = "UC-SHE-SIDE-MENU-FL02-ABOUT"
        const val SIDE_MENU_TERMS_AND_CONDITIONS = "UC-SHE-SIDE-MENU-FL03-TERMS"
        const val SIDE_MENU_PRIVACY_POLICY = "UC-SHE-SIDE-MENU-FL04-PRIVACY-POLICY"
        const val SIDE_MENU_CONTACT_US = "UC-SHE-SIDE-MENU-FL05-CONTACT-US"
        const val SIDE_MENU_LOGOUT = "UC-SHE-SIDE-MENU-FL06-LOGOUT"
        const val SIDE_MENU_937_COMPLAINTS = "UC-SHE-937-001-FL01"
        const val SIDE_MENU_937_ADD_COMPLAINT = "UC-SHE-937-002-FL01"
    }
    
    object Appointment {
        const val APPOINTMENT_FEATURE = "UC-SHE-APPOINTMENT"
        
        object Upcoming {
            const val APPOINTMENT_UPCOMING = "UC-SHE-APPOINTMENT-FL01-UPCOMING"
            
            const val APPOINTMENT_UPCOMING_CALL = "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL01-CALL"
            const val APPOINTMENT_SELF_CHECK_IN_MESSAGE =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL02-CHECK-IN-MESSAGE"
            const val APPOINTMENT_SELF_CHECK_IN_BUTTON =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL03-CHECK-IN-BUTTON"
            const val APPOINTMENT_ADD_COMPANION_FLAG =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-ADD-COMPANION"
            const val APPOINTMENT_VERSION_3_FLAG =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-GET-APPOINTMENT-V3"
            const val APPOINTMENT_ADD_COMPANION_INSIDE_CALL_FLAG =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-ADD-COMPANION-IN-CALL"
            const val APPOINTMENT_EDIT_COMPANION_FLAG =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-EDIT-COMPANION"
            const val APPOINTMENT_REMOVE_COMPANION_FLAG =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-REMOVE-COMPANION"
            const val APPOINTMENT_UPCOMING_IN_PERSON_VIRTUAL_DETAILS =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL02-IN-PERSON-VIRTUAL-DETAILS"
            const val APPOINTMENT_UPCOMING_IN_PERSON_VIRTUAL_DETAILS_CALL =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL02-IN-PERSON-VIRTUAL-DETAILS-FL01-CALL"
            const val APPOINTMENT_UPCOMING_IN_PERSON_VIRTUAL_DETAILS_RESCHEDULE =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL02-IN-PERSON-VIRTUAL-DETAILS-FL02-RESCHEDULE"
            const val APPOINTMENT_UPCOMING_IN_PERSON_VIRTUAL_DETAILS_CANCEL =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL02-IN-PERSON-VIRTUAL-DETAILS-FL03-CANCEL"
            
            const val APPOINTMENT_UPCOMING_VIRUS_VACCINE_DETAILS =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL03-VIRUS-VACCINE-DETAILS"
            const val APPOINTMENT_UPCOMING_VIRUS_VACCINE_DETAILS_RESCHEDULE =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL03-VIRUS-VACCINE-DETAILS-FL01-RESCHEDULE"
            const val APPOINTMENT_UPCOMING_VIRUS_VACCINE_DETAILS_CANCEL =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL03-VIRUS-VACCINE-DETAILS-FL02-CANCEL"
            
            const val APPOINTMENT_UPCOMING_VIRUS_TEST_DETAILS =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-VIRUS-TEST-DETAILS"
            const val APPOINTMENT_UPCOMING_VIRUS_TEST_DETAILS_CANCEL =
                "UC-SHE-APPOINTMENT-FL01-UPCOMING-FL04-VIRUS-TEST-DETAILS-FL01-CANCEL"
        }
        
        object Past {
            const val APPOINTMENT_PAST = "UC-SHE-APPOINTMENT-FL02-PAST"
            const val APPOINTMENT_PAST_DETAILS = "UC-SHE-APPOINTMENT-FL02-PAST-FL01-DETAILS"
        }
        
        object AddNewAppointment {
            const val APPOINTMENT_ADD_APPOINTMENT = "UC-SHE-APPOINTMENT-FL03-ADD-APPOINTMENT"
            const val APPOINTMENT_IMMEDIATE_CONSULTATION =
                "UC-SHE-APPOINTMENT-FL003-ADD-APPOINTMENT-FL01-IMMEDIATE-CONSULTATION"
            const val APPOINTMENT_IMMEDIATE_CONSULTATION_CHAT_GPT =
                "UC-SHE-APPOINTMENT-FL003-ADD-APPOINTMENT-FL01-IMMEDIATE-CONSULTATION-FL01-CHAT-GPT"
            const val APPOINTMENT_IN_PERSON =
                "UC-SHE-APPOINTMENT-FL003-ADD-APPOINTMENT-FL02-IMMEDIATE-IN-PERSON"
            const val APPOINTMENT_VIRTUAL =
                "UC-SHE-APPOINTMENT-FL003-ADD-APPOINTMENT-FL03-VIRTUAL"
            const val APPOINTMENT_CHILD_VACCINE =
                "UC-SHE-APPOINTMENT-FL003-ADD-APPOINTMENT-FL04-CHILD-VACCINE"
            const val APPOINTMENT_ADULT_VACCINE =
                "UC-SHE-APPOINTMENT-FL003-ADD-APPOINTMENT-FL05-ADULT-VACCINE"
        }
    }
    
    object MyHealth {
        const val MY_HEALTH = "UC-SHE-MY-HEALTH"
        const val MY_HEALTH_VISITOR_ERROR = "UC-SHE-MY-HEALTH-VISITOR-ERROR"
        const val MY_HEALTH_PREVENTION = "UC-SHE-MY-HEALTH-PREVENTION"
        const val MY_HEALTH_NEPHIS_CONSENT = "UC-SHE-MY-HEALTH-NEPHIS-CONSENT"
        const val MY_HEALTH_NEPHIS_PARTNER = "UC-SHE-MY-HEALTH-NEPHIS-CONSENT-PARTNER"
        const val MY_HEALTH_NEPHIS_PARTNER_COUNT = "UC-SHE-MY-HEALTH-NEPHIS-PARTNER-COUNT"
        const val MY_HEALTH_SHARE_PROFILE_HEALTH = "UC-SHE-MY-HEALTH-SHARE-PROFILE-HEALTH"
        const val HEALTH_SUMMARY_DELETE_DEPENDENT = "UC-SHE-MY-FAMILY-FL02-DELETE-MEMBER"
        const val MY_HEALTH_TOOL_TIP = "UC-SHE-OB-001-Fl01"
        
        object MedicalReports {
            const val MEDICAL_REPORTS = "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT"
            const val MEDICAL_REPORTS_SICK_LEAVE =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL01-SICK-LEAVE"
            const val MEDICAL_REPORTS_SICK_LEAVE_PDF =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL01-SICK-LEAVE-FL01-PDF"
            const val MEDICAL_REPORTS_IMAGING = "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL02-IMAGING"
            const val MEDICAL_REPORTS_DOCUMENTS =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL03-DOCUMENTS"
            const val MEDICAL_REPORTS_PRE_MARRIAGE =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL04-PRE-MARRIAGE"
            const val MEDICAL_REPORTS_SCHOOL_TESTS =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL05-SCHOOL-TESTS"
            const val MEDICAL_REPORTS_SCHOOL_TESTS_SCREENING =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL05-SCHOOL-TESTS-FL01-SCREENING"
            const val MEDICAL_REPORTS_SCHOOL_TESTS_PRE_SCHOOL =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL05-SCHOOL-TEST-FL02-PRE-SCHOOL"
            const val MEDICAL_REPORTS_OTHER_TESTS =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL06-OTHER-TESTS"
            const val MEDICAL_REPORTS_OTHER_TESTS_HEALTH_CERTIFICATE =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL06-OTHER-TESTS-FL01-HEALTH-CERTIFICATE"
            const val MEDICAL_REPORTS_OTHER_TESTS_DRIVING_LICENCE =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL06-OTHER-TESTS-FL02-DRIVING-LICENCE"
            const val MEDICAL_REPORTS_OTHER_TESTS_IQAMA_TEST =
                "UC-SHE-MY-HEALTH-FL01-MEDICAL-REPORT-FL06-OTHER-TESTS-FL03_IQAMA-TEST"
        }
        
        object Prescriptions {
            const val PRESCRIPTIONS = "UC-SHE-MY-HEALTH-FL02-PRESCRIPTIONS"
            const val PRESCRIPTIONS_CURRENT = "UC-SHE-MY-HEALTH-FL02-PRESCRIPTIONS-FL01-CURRENT"
            const val PRESCRIPTIONS_PREVIOUS = "UC-SHE-MY-HEALTH-FL02-PRESCRIPTIONS-FL02-PREVIOUS"
            const val PRESCRIPTIONS_DETAILS =
                "UC-SHE-MY-HEALTH-FL02-PRESCRIPTIONS-FL01-PRESCRIPTIONS-DETAILS"
            const val PRESCRIPTIONS_MEDICATION =
                "UC-SHE-MY-HEALTH-FL02-PRESCRIPTIONS-FL02-MEDICATION"
        }
        
        object WomanHealth {
            const val WOMAN_HEALTH = "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH"
            
            const val WOMAN_HEALTH_PREGNANCY_DATA =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL01-PREGNANCY-DATA"
            
            const val WOMAN_HEALTH_PREGNANCY_RISK =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL02-PREGNANCY-RISK"
            const val WOMAN_HEALTH_PREGNANCY_RISK_APPOINTMENT =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL02-PREGNANCY-RISK-FL04-APPOINTMENT"
            
            const val WOMAN_HEALTH_KICKS = "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL03-KICKS"
            
            const val WOMAN_HEALTH_MY_DIARY = "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL04-MY-DIARY"
            const val WOMAN_HEALTH_MY_DIARY_ADD =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL04-MY-DIARY-FL01-ADD"
            const val WOMAN_HEALTH_MY_DIARY_EDIT =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL04-MY-DIARY-FL02-EDIT"
            
            const val WOMAN_HEALTH_CHECKLIST = "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL05-CHECKLIST"
            const val WOMAN_HEALTH_CHECKLIST_ADD =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL05-CHECKLIST-FL01-ADD"
            const val WOMAN_HEALTH_CHECKLIST_EDIT =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL05-CHECKLIST-FL02-EDIT"
            
            const val WOMAN_HEALTH_WEEKLY_TIPS =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL06-WEEKLY-TIPS"
            
            const val WOMAN_HEALTH_CONTRACTIONS =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL07-CONTRACTIONS"
            
            const val WOMAN_HEALTH_PREGNANCY_DETAILS =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL08-PREGNANCY-DETAILS"
            const val WOMAN_HEALTH_PREGNANCY_DETAILS_EDIT_DATE =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL08-PREGNANCY-DETAILS-FL01-EDIT-DATE"
            const val WOMAN_HEALTH_PREGNANCY_DETAILS_EDIT_DATA =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL08-PREGNANCY-DETAILS-FL02-EDIT-DATA"
            const val WOMAN_HEALTH_PREGNANCY_DETAILS_LOSE_BABY =
                "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL08-PREGNANCY-DETAILS-FL02-LOSE-BABY"
            
            const val WOMAN_HEALTH_BIRTH_PLAN = "UC-SHE-MY-HEALTH-FL03-WOMAN-HEALTH-FL09-BIRTH-PLAN"
        }
        
        object Medication {
            const val MEDICATIONS = "UC-SHE-MY-HEALTH-FL04-MEDICATIONS"
            const val MEDICATIONS_VIEW_PREVIOUS_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL01-VIEW-PREVIOUS-MEDICATIONS"
            const val MEDICATIONS_VIEW_CURRENT_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL02-VIEW-CURRENT-MEDICATIONS"
            const val MEDICATIONS_ADD_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL03-ADD-MEDICATIONS"
            const val MEDICATIONS_EDIT_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL04-EDIT-MEDICATIONS"
            const val MEDICATIONS_DELETE_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL05-DELETE-MEDICATIONS"
            const val MEDICATIONS_STOP_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL06-STOP-MEDICATIONS"
            const val MEDICATIONS_REUSE_MEDICATIONS =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL07-REUSE-MEDICATIONS"
            const val MEDICATIONS_SEARCH =
                "UC-SHE-MY-HEALTH-FL04-MEDICATIONS-FL08-SEARCH-MEDICATIONS"
        }
        
        object HealthRecord {
            const val HEALTH_RECORD = "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD"
            const val HEALTH_RECORD_BLOOD_TYPE =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL01-BLOOD-TYPE"
            const val HEALTH_RECORD_HEIGHT = "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL02-HEIGHT"
            const val HEALTH_RECORD_WEIGHT = "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL02-WEIGHT"
            const val HEALTH_RECORD_VITAL_SIGNS =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL03-VITAL-SIGNS"
            const val HEALTH_RECORD_VITAL_SIGNS_HYPER_TENSION =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL03-VITAL-SIGNS-FL01-HYPER-TENSION"
            const val HEALTH_RECORD_VITAL_SIGNS_BLOOD_GLUCOSE =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL03-VITAL-SIGNS-FL02-BLOOD-GLUCOSE"
            const val HEALTH_RECORD_VITAL_SIGNS_BLOOD_PRESSURE =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL03-VITAL-SIGNS-FL03-BLOOD-PRESSURE"
            const val HEALTH_RECORD_VITAL_SIGNS_WAIST_LINE =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL03-VITAL-SIGNS-FL04-WAIST-LINE"
            const val HEALTH_RECORD_VITAL_SIGNS_BMI =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL03-VITAL-SIGNS-FL05-BMI"
            const val HEALTH_RECORD_HEALTH_CONDITION =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL04-HEALTH-CONDITION"
            const val HEALTH_RECORD_HEALTH_CONDITION_ADD =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL04-HEALTH-CONDITION-FL01-ADD"
            const val HEALTH_RECORD_HEALTH_CONDITION_DELTE =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL04-HEALTH-CONDITION-FL02-DELETE"
            const val HEALTH_RECORD_HEALTH_CONDITION_NPHIES =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL04-HEALTH-CONDITION-FL02-NPHIES"
            
            const val HEALTH_RECORD_FAMILY_HISTORY =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL05-FAMILY-HISTORY"
            const val HEALTH_RECORD_FAMILY_HISTORY_ADD =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL05-FAMILY-HISTORY-FL01-ADD"
            const val HEALTH_RECORD_ALLERGIES = "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL06-ALLERGIES"
            const val HEALTH_RECORD_ALLERGIES_ADD =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL06-ALLERGIES-FL01-ADD"
            const val HEALTH_RECORD_ALLERGIES_NPHIES =
                "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL06-ALLERGIES-FL02-NPHIES"
            const val HEALTH_RECORD_SHARE_PDF = "UC-SHE-MY-HEALTH-FL05-HEALTH-RECORD-FL07-SHARE-PDF"
        }
        
        object WalletList {
            const val WALLET_LIST = "UC-SHE-MY-HEALTH-FL06-WALLET-LIST"
            const val WALLET_LIST_DETAILS =
                "UC-SHE-MY-HEALTH-FL06-WALLET-LIST-FL01-DETAILS"
            const val WALLET_LIST_SHARE_PDF = "UC-SHE-MY-HEALTH-FL06-WALLET-LIST-FL02-SHARE_PDF"
        }
        
        object PersonalProfile {
            const val PERSONAL_PROFILE = "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE"
            const val PERSONAL_PROFILE_EMAIL = "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE-FL01-EMAIL"
            const val PERSONAL_PROFILE_MARITAL_STATUS =
                "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE-FL02-MARITAL-STATUS"
            const val PERSONAL_PROFILE_ADDRESS =
                "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE-FL03-ADDRESS"
            const val PERSONAL_PROFILE_HEALTH_CENTER =
                "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE-FL04-HEALTH-CENTER"
            const val PERSONAL_PROFILE_CELL_PHONE =
                "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE-FL05-PHONE"
            const val PERSONAL_PROFILE_NAFAZ = "UC-SHE-MY-HEALTH-FL07-PERSONAL-PROFILE-FL05-NAFAZ"
        }
        
        object Visits {
            const val VISITS = "UC-SHE-MY-HEALTH-FL08-VISITS"
            const val VISITS_FILTER = "UC-SHE-MY-HEALTH-FL08-VISITS-FL01-VISITS-FILTER"
            const val VISITS_SEARCH = "UC-SHE-MY-HEALTH-FL08-VISITS-FL02-VISITS-SEARCH"
            const val VISITS_DETAILS = "UC-SHE-MY-HEALTH-FL08-VISITS-FL03-VISITS-DETAILS"
            const val VISITS_DETAILS_VISIT_INFO =
                "UC-SHE-MY-HEALTH-FL08-VISITS-FL03-VISITS-DETAILS-FL01-VISIT-INFO"
            const val VISITS_DETAILS_MEDICAL_PRESCRIPTION =
                "UC-SHE-MY-HEALTH-FL08-VISITS-FL03-VISITS-DETAILS-FL02-MEDICAL-PRESCRIPTION"
            const val VISITS_DETAILS_IMAGING_REPORT =
                "UC-SHE-MY-HEALTH-FL08-VISITS-FL03-VISITS-DETAILS-FL03-IMAGING-REPORT"
            const val VISITS_DETAILS_LAB =
                "UC-SHE-MY-HEALTH-FL08-VISITS-FL03-VISITS-DETAILS-FL04-LAB"
            const val VISITS_PRESCRIPTION_DETAILS =
                "UC-SHE-VIS-MED-003-FL01"
        }
        
        object Lab {
            const val LAB = "UC-SHE-MY-HEALTH-FL09-LAB"
            const val LAB_DETAILS = "UC-SHE-MY-HEALTH-FL09-LAB-FL01-LAB-DETAILS"
            const val LAB_DOCTOR_CHAT = "UC-SHE-MY-HEALTH-FL09-LAB-FL03-DOCTOR-CHAT"
        }
        
        object MyDoctor {
            const val MY_DOCTOR = "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR"
            const val MY_DOCTOR_ASSIGN_TEAM = "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR-FL01-ASSIGN-TEAM"
            const val MY_DOCTOR_CHANGE_DOCTOR = "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR-FL02-CHANGE-DOCTOR"
            const val MY_DOCTOR_NEW_APPOINTMENT =
                "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR-FL03-NEW-APPOINTMENT"
            const val MY_DOCTOR_CHAT = "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR-FL04-CHAT"
            const val MY_DOCTOR_CHAT_BOT = "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR-FL05-CHAT-BOT"
            const val MY_DOCTOR_CHAT_TIMER_COUNT = "UC-SHE-MY-HEALTH-FL10-MY-DOCTOR-CHAT-TIMER"
            const val MY_DOCTOR_CHAT_RECORDER = "UC-SHE-CT-003-FL01"
        }
        
        object Procedures {
            const val PROCEDURES = "UC-SHE-MY-HEALTH-FL11-PROCEDURE"
        }
        
        object Vaccines {
            const val VACCINES = "UC-SHE-MY-HEALTH-FL12-VACCINES"
            const val VACCINES_GENERAL = "UC-SHE-MY-HEALTH-FL12-VACCINES-FL01-GENERAL"
            const val VACCINES_GENERAL_NEW_APPOINTMENT =
                "UC-SHE-MY-HEALTH-FL12-VACCINES-FL01-GENERAL-FL01-NEW-APPOINTMENT"
            const val VACCINES_GENERAL_DOWNLOAD_REPORT =
                "UC-SHE-MY-HEALTH-FL12-VACCINES-FL01-GENERAL-FL02-DOWNLOAD-REPORT"
            
            const val VACCINES_CHILDREN = "UC-SHE-MY-HEALTH-FL12-VACCINES-FL02-CHILDREN"
            const val VACCINES_CHILDREN_NEW_APPOINTMENT =
                "UC-SHE-MY-HEALTH-FL12-VACCINES-FL02-CHILDREN-FL01-NEW-APPOINTMENT"
            const val VACCINES_CHILDREN_DOWNLOAD_REPORT =
                "UC-SHE-MY-HEALTH-FL12-VACCINES-FL02-CHILDREN-FL02-DOWNLOAD-REPORT"
            const val VACCINES_CHILDREN_REGISTER_VIRUS =
                "UC-SHE-MY-HEALTH-FL12-VACCINES-FL02-CHILDREN-FL03-REGISTER-VIRUS"
        }
        
        object InsuranceApproval {
            const val INSURANCE_APPROVAL = "UC-SHE-MY-HEALTH-FL13-INSURANCE-APPROVAL"
            const val INSURANCE_APPROVAL_DETAILS = "UC-SHE-MY-HEALTH-FL13-INSURANCE-APPROVAL-FL01-APPROVAL-DETAILS"
            const val INSURANCE_APPROVALS_LIST = "UC-SHE-MY-HEALTH-FL13-INSURANCE-APPROVAL-FL01-APPROVALS-LIST"
            const val INSURANCE_TRANSACTIONS_LIST = "UC-SHE-MY-HEALTH-FL13-INSURANCE-APPROVAL-FL02-TRANSACTIONS-LIST"
        }
        
        object SoftLaunch {
            const val SOFT_LAUNCH = "UC-SHE-MY-HEALTH-FL14-SOFT-LAUNCH"
        }
    }
    
    object As3afny {
        const val AS3FNY_VIEW_REPORTS = "UC-SHE-AS3AFNY-FL02-VIEW-REPORTS"
        const val AS3FNY_VIEW_REPORTS_CURRENT = "UC-SHE-AS3AFNY-FL02-VIEW-REPORTS-FL01-CURRENT"
        const val AS3FNY_VIEW_REPORTS_PREVIOUS =
            "UC-SHE-AS3AFNY-FL02-VIEW-REPORTS-FL02-PREVIOUS"
        const val AS3FNY_ADD_REPORTS = "UC-SHE-AS3AFNY-FL02-ADD-REPORT"
    }
    
    object DailyActivity {
        const val DAILY_ACTIVITY_UPDATE_TARGET = "UC-SHE-DAILY-ACTIVITY-FL01-UPDATE-TARGET"
        
        const val DAILY_ACTIVITY_CAMPAIGNS = "UC-SHE-DAILY-ACTIVITY-FL02-CAMPAIGNS"
        const val DAILY_ACTIVITY_CAMPAIGNS_WITHDRAW =
            "UC-SHE-DAILY-ACTIVITY-FL02-CAMPAIGNS-FL01-WITHDRAW"
        
        const val DAILY_ACTIVITY_CHALLENGES = "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES"
        
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE"
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE_JOINED_DETAILS =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE-FL01-JOINED-FL01-DETAILS"
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE_JOINED_EDIT =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE-FL01-JOINED-FL01-DETAILS-EDIT"
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE_JOINED_DELETE =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE-FL01-JOINED-FL01-DETAILS-DELETE"
        
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE_PENDING_DETAILS =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE-FL02-PENDING-FL01-DETAILS"
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE_PENDING_JOIN =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE-FL02-PENDING-FL01-DETAILS-JOIN"
        const val DAILY_ACTIVITY_CHALLENGES_ACTIVE_PENDING_DECLINE =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-ACTIVE-FL02-PENDING-FL01-DETAILS-DECLINE"
        
        const val DAILY_ACTIVITY_CHALLENGES_PREVIOUS =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL02-PREVIOUS"
        const val DAILY_ACTIVITY_CHALLENGES_PREVIOUS_DETAILS =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-PREVIOUS-FL01-DETAILS"
        const val DAILY_ACTIVITY_CHALLENGES_PREVIOUS_DETAILS_REACTIVATE =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL01-PREVIOUS-FL01-DETAILS-FL01-REACTIVATE"
        
        const val DAILY_ACTIVITY_CHALLENGES_NEW =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL03-NEW"
        const val DAILY_ACTIVITY_CHALLENGES_NEW_ADD_PARTICIPANT =
            "UC-SHE-DAILY-ACTIVITY-FL03-CHALLENGES-FL03-NEW-FL01-ADD-PARTICIPANT"
        
        const val DAILY_ACTIVITY_ACHIEVEMENTS = "UC-SHE-DAILY-ACTIVITY-FL04-ACHIEVEMENTS"
    }
    
    object MyFamily {
        const val MY_FAMILY_FEATURE = "UC-SHE-MY-FAMILY"
        
        object AddNewMember {
            const val MY_FAMILY_ADD_MEMBER = "UC-SHE-MY-FAMILY-FL01-ADD-MEMBER"
            const val MY_FAMILY_ADD_MEMBER_MANUAL =
                "UC-SHE-MY-FAMILY-FL01-ADD-MEMBER-FL01-ADD-MANUAL"
            const val MY_FAMILY_ADD_MEMBER_CHILDREN =
                "UC-SHE-MY-FAMILY-FL01-ADD-MEMBER-FL02-CHILDREN"
            const val MY_FAMILY_ADD_MEMBER_ADULT = "UC-SHE-MY-FAMILY-FL01-ADD-MEMBER-FL03-ADULT"
        }
        
        object MembersRequest {
            const val MY_FAMILY_MEMBER_REQUEST = "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST"
            const val MY_FAMILY_MEMBER_REQUEST_SENT =
                "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST-FL01-SENT-REQUEST"
            const val MY_FAMILY_MEMBER_REQUEST_RECEIVED =
                "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST-FL02-RECEIVED-REQUEST"
            const val MY_FAMILY_MEMBER_REQUEST_RECEIVED_STOP =
                "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST-FL02-RECEIVED-REQUEST-FL01-STOP"
            const val MY_FAMILY_MEMBER_REQUEST_RECEIVED_ACCEPT =
                "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST-FL02-RECEIVED-REQUEST-FL02-ACCEPT"
            const val MY_FAMILY_MEMBER_REQUEST_RECEIVED_REJECT =
                "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST-FL02-RECEIVED-REQUEST-FL03-REJECT"
            const val MY_FAMILY_MEMBER_REQUEST_RECEIVED_RESEND_VERIFICATION =
                "UC-SHE-MY-FAMILY-FL02-MEMBER-REQUEST-FL02-RECEIVED-REQUEST-FL04-RESEND_VERIFICATION"
        }
        
        object MemberHealthProfile {
            const val MY_FAMILY_MEMBER_HEALTH_PROFILE =
                "UC-SHE-MY-FAMILY-FL03-MEMBER-HEALTH-PROFILE"
            const val MY_FAMILY_MEMBER_HEALTH_PROFILE_DELETE =
                "UC-SHE-MY-FAMILY-FL03-MEMBER-HEALTH-PROFILE-FL01-DELETE-PROFILE"
            const val MY_FAMILY_MEMBER_HEALTH_PROFILE_CHANGE =
                "UC-SHE-MY-FAMILY-FL03-MEMBER-HEALTH-PROFILE-FL02-CHANGE-PROFILE"
            const val MY_FAMILY_MEMBER_HEALTH_PROFILE_SUMMARY =
                "UC-SHE-MY-FAMILY-FL03-MEMBER-HEALTH-PROFILE-FL03-CHANGE-SUMMARY"
        }
    }
    
    object WellBeing {
        const val WELL_BEING_FEATURE = "UC-SHE-WELL-BEING"
        const val WELL_BEING_DAILY_ACTIVITY = "UC-SHE-WELL-BEING-FL01-DAILY-ACTIVITY"
        const val WELL_BEING_EDUCATIONAL_CONTENT = "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT"
        const val WELL_BEING_EDUCATIONAL_CONTENT_ALL =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL01-ALL"
        const val WELL_BEING_EDUCATIONAL_CONTENT_ALL_PERSONALIZED =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL01-ALL-FL01-PERSONALIZED"
        const val WELL_BEING_EDUCATIONAL_CONTENT_COLUMNS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL02-COLUMNS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_COLUMNS_ARTICLES =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL02-COLUMNS-FL01-ARTICLES"
        const val WELL_BEING_EDUCATIONAL_CONTENT_COLUMNS_FAQS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL02-COLUMNS-FL02-FAQS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_COLUMNS_TIPS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL02-COLUMNS-FL03-TIPS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_MEDIA =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL03-MEDIA"
        const val WELL_BEING_EDUCATIONAL_CONTENT_MEDIA_VIDEOS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL03-MEDIA-FL01-VIDEOS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_MEDIA_EVENTS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL03-MEDIA-FL02-EVENTS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_MEDIA_POSTS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL03-MEDIA-FL03-POSTS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_DETAILS =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL04-CONTENT-DETAILS"
        const val WELL_BEING_EDUCATIONAL_CONTENT_SEARCH =
            "UC-SHE-WELL-BEING-FL02-EDUCATIONAL-CONTENT-FL05-SEARCH"
    }
    
    object Landing {
        const val LANDING_CREATE_ACCOUNT = "UC-SHE-LANDING-FL01-CREATE-ACCOUNT"
        const val LANDING_CREATE_ACCOUNT_VISITOR = "UC-SHE-LANDING-FL01-CREATE-ACCOUNT-FL01-VISITOR"
        const val LANDING_CREATE_ACCOUNT_USER = "UC-SHE-LANDING-FL02-CREATE-ACCOUNT-FL02-USER"
        
        const val LANDING_TERMS_CONDITIONS = "UC-SHE-LANDING-FL02-TERMS-CONDITIONS"
        const val LANDING_PRIVACY_POLICY = "UC-SHE-LANDING-FL03-PRIVACY-POLICY"
        const val LANDING_CONTACT_US = "UC-SHE-LANDING-FL04-CONTACT-US"
        
        const val LANDING_LOGIN = "UC-SHE-LANDING-FL05-LOGIN"
        const val LANDING_LOGIN_VISITOR = "UC-SHE-LANDING-FL05-LOGIN-FL01-VISITOR"
        const val LANDING_LOGIN_VISITOR_UPDATE_NUMBER =
            "UC-SHE-LANDING-FL05-LOGIN-FL01-VISITOR-FL01-UPDATE-NUMBER"
        const val LANDING_LOGIN_VISITOR_FORGET_PASSWORD =
            "UC-SHE-LANDING-FL05-LOGIN-FL01-VISITOR-FL02-FORGET-PASSWORD"
        const val LANDING_LOGIN_VISITOR_PASSPORT =
            "UC-SHE-LANDING-FL05-LOGIN-FL01-VISITOR-FL03-PASSPORT"
        const val LANDING_LOGIN_VISITOR_BORDER_NUMBER =
            "UC-SHE-LANDING-FL05-LOGIN-FL01-VISITOR-FL04-BORDER-NUMBER"
        
        const val LANDING_LOGIN_CITIZEN = "UC-SHE-LANDING-FL05-LOGIN-FL02-CITIZEN"
        const val LANDING_LOGIN_CITIZEN_UPDATE_NUMBER =
            "UC-SHE-LANDING-FL05-LOGIN-FL02-CITIZEN-FL01-UPDATE-NUMBER"
        const val LANDING_LOGIN_CITIZEN_FORGET_PASSWORD =
            "UC-SHE-LANDING-FL05-LOGIN-FL02-CITIZEN-FL02-FORGET-PASSWORD"
    }
    
    object PartnersPage{
        const val PARTNERS_PAGE = "UC-SHE-EMP-001-Fl01"
    }
}