package org.alimapps.letsconnect.core.common.navigation

object NavArgs {
    const val patientNationalId = "patientNationalId"
    const val sessionId = "sessionId"
    const val sessionItemId = "sessionItemId"
    const val CHAT_CLOSER_ID = "chatCloserId"
    const val appointmentJson = "appointmentJson"
    const val physicianId = "physicianId"
    const val physicianName = "physicianName"
    const val msg = "msg"
    const val sheetTitle = "sheetTitle"
    const val teamId = "teamId"
    const val fromTeamCare = "fromTeamCare"
    const val nationalId = "nationalId"
    const val fromLogIn = "fromLogIn"
    const val nafathSubmitRequest = "nafathSubmitRequest"
    const val nafathInformationRequest = "nafath_request"
    const val userFilter = "userFilter"
    const val CALL_TYPE = "callType"
    const val FEATURE_NAME = "featureName"
    const val ENABLE_ADD_COMPANION = "enableAddCompanion"
    const val WAITING_TIME = "waitingTimeMinutes"
    const val CHANNEL_ID = "sessionId"
    const val VISIT_ID = "visitId"
    const val LAB_ID = "labID"
    const val TEST_CODE = "testCode"
    const val VISIT_MODEL = "uiVisitModel"
    const val VISIT_DATE = "visitDate"
    const val SUCCESS_SCREEN_TITLE= "SUCCESS_SCREEN_TITLE"
    const val WEB_VIEW_URL = "url"
    const val WEB_VIEW_TITLE = "title"
    const val WEB_VIEW_SHOW_DEPENDENT_FILTER = "showDependentFilter"
    const val WEB_VIEW_TYPE = "WEB_VIEW_TYPE"
    const val NOTIFICATION_ID = "notificationId"
    const val CHALLENGE_ID = "challengeId"
    const val GROUP_ID = "groupId"
    const val DEPENDENT_ID = "dependentId"
    const val DEPENDENT_REQUEST_TAP = "tab"
    const val campaignModel = "campaignModel"
    const val isEditMode = "isEditMode"
    const val wifeNationalId = "wifeNationalId"
    const val challengeModel = "challengeModel"
    const val isActiveChallenge = "isActiveChallenge"
    const val isChallengeExpired = "isChallengeExpired"
    const val SHOW_CHAT_SURVEY = "showChatSurvey"
    const val ENCOUNTER_ID ="encounterID"
    const val ORDER_ID ="orderID"
    const val MEDICATION_ID ="medicationID"
    const val MAIN_LAB_FLAG = "mainLabFlag"
    const val LAB_RESULT_FLAG = "labResultFlag"
    const val MEDICAL_REPORT_WITH_TYPE = "medicalReportId"
    const val MEDICATION_PRESCRIPTION_FLAG = "medicationPrescriptionFlag"
    const val REFILL_ORDERS_FLAG = "refillOrdersFlag"
    const val TASK_ID = "taskId"
    const val SOURCE = "source"
    const val TYPE = "type"
    const val INSURANCE_JSON = "insuranceApproval"
    const val PRESCRIPTION_ITEM= "prescriptionItem"

    const val IS_OPEN_UPDATE_TARGET_SHEET= "isUpdateTarget"

    const val REQUEST_ID = "requestId"
    const val TAB_POSITION = "tabPosition"

    const val PAYMENT_PARAMS = "params"
    const val PAYMENT_REDIRECT_URL = "redirectUrl"


    const val PDF_URL = "PDF_URL"
    const val PDF_HEADER_TITLE = "header_title"
    const val PDF_AUTH_REQUIRED = "auth_required"
    const val PDF_WITH_V2 = "withV2"
    const val PDF_DEPENDENT_NATIONAL_ID = "dependent_national_id"
}
